# This file configures the hello-world app which serves public web traffic.
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: network
spec:
  replicas: 1
  selector:
    matchLabels:
      app: network
  template:
    metadata:
      labels:
        app: network
    spec:
      containers:
      - name: network
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/storied-parser-275211/network:latest
        # This app listens  on port 8080 for web traffic by default.
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"